data:
  dataset: Shapes3D
  path: data/ShapeNet
  class: null
  data_type: img
  input_type: pointcloud
  dim: 3
  num_points: 1000
  num_gt_points: 1000
  num_offset: 1
  img_size: null
  n_views_input: 20
  n_views_per_iter: 2
  pointcloud_noise: 0
  pointcloud_file: pointcloud.npz
  pointcloud_outlier_ratio: 0
  fixed_scale: 0
  train_split: train
  val_split: val
  test_split: test
  points_file: null
  points_iou_file: points.npz
  points_unpackbits: true
  padding: 0.1
  multi_files: null
  gt_mesh: null
  zero_level: 0
  only_single: False
  sample_only_floor: False
model:
  apply_sigmoid: True
  grid_res: 128 # poisson grid resolution
  psr_sigma: 0
  psr_tanh: False
  normal_normalize: False
  raster: {}
  renderer: {}
  encoder: null
  predict_normal: True
  predict_offset: True
  s_offset: 0.001
  local_coord: True
  encoder_kwargs: {}
  unet3d: False
  unet3d_kwargs: {}
  multi_gpu: false
  rotate_matrix: false
  c_dim: 512
  sphere_radius: 0.2
train:
  lr: 1e-3
  lr_pcl: 2e-2
  input_mesh: ''
  out_dir:  out/default
  subsample_vertex: False
  batch_size: 1
  n_grow_points: 0
  resample_every: 0
  l_weight: {}
  w_reg_point: 0
  w_psr: 0
  w_raw: 0 # train with raw point cloud
  gauss_weight: 0
  n_sup_point: 0
  w_normals: 0
  total_epochs: 1000
  print_every: 20
  visualize_every: 1000
  save_every: 1000
  vis_vert_color: True
  o3d_show: False
  o3d_vis_pcl: True
  o3d_window_size: 540
  vis_rendering: False
  vis_psr: False
  save_video: False
  exp_mesh: True
  exp_pcl: True
  checkpoint_every: 1000
  validate_every: 2000000
  backup_every: 100000
  timestamp: False # add timestamp to out_dir name
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 0
  n_workers_val: 0
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: false
  model_file: model_best.pt
generation:
  batch_size: 100000
  exp_gt: False
  exp_oracle: false
  exp_input: False
  vis_n_outputs: 10
  generate_mesh: true
  generate_pointcloud: true
  generation_dir: generation
  copy_input: true
  use_sampling: false
  psr_resolution: 0
  psr_sigma: 0
